#!/usr/bin/env bash

set -eu

TTY=

if [ -t 1 ] ; then
	TTY=-t
fi

docker run -i $TTY \
	--init \
	-u "$(id -u):$(id -g)" \
	-v "$PWD:/app" \
	-p "3000:3000" \
	-w "/app" \
	-e "BASE_PATH=$BASE_PATH" \
	dayoff-crystal crystal "$@"
